#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""Dictionary of constants used throughout the application."""

# Achievement Constants
AC_KEYSTONE_MASTER = 11162
AC_KEYSTONE_CONQUEROR = 11185
AC_KEYSTONE_CHALLENGER = 11184
AC_ARENA_CHALLENGER = 2090
AC_ARENA_RIVAL = 2093
AC_ARENA_DUELIST = 2092
AC_ARENA_GLADIATOR = 2091
AC_AOTC_UD = 12536
AC_CE_UD = 12535
AC_HIGH_WARLORD = 5356
AC_CHAMPION = 5353
AC_FIRST_SERGEANT = 5349
AC_GRAND_MARSHALL = 5343
AC_LIEUTENANT_COMMANDER = 5339
AC_SERGEANT_MAJOR = 5334

# Achievement Title Constants
AC_HIGH_WARLORD_NAME = 'High Warlord'
AC_CHAMPION_NAME = 'Champion'
AC_FIRST_SERGEANT_NAME = 'First Sergeant'
AC_GRAND_MARSHALL_NAME = 'Grand Marshall'
AC_LIEAUTENANT_COMMANDER_NAME = 'Lieutenant Commander'
AC_SERGEANT_MAJOR_NAME = 'Sergeant Major'

# Raid Constants
RAID_UD = 9389

# Faction Constants
FACTION_HORDE = 1
FACTION_ALLIANCE = 0

# Faction Name Constants
FACTION_HORDE_NAME = 'Horde'
FACTION_ALLIANCE_NAME = 'Alliance'

# Classs Constants
CLASS_WARRIOR = 1
CLASS_PALADIN = 2
CLASS_HUNTER = 3
CLASS_ROGUE = 4
CLASS_PRIEST = 5
CLASS_DEATH_KNIGHT = 6
CLASS_SHAMAN = 7
CLASS_MAGE = 8
CLASS_WARLOCK = 9
CLASS_MONK = 10
CLASS_DRUID = 11
CLASS_DEMON_HUNTER = 12

# Class Name Constants
CLASS_WARRIOR_NAME = 'Warrior'
CLASS_PALADIN_NAME = 'Paladin'
CLASS_HUNTER_NAME = 'Hunter'
CLASS_ROGUE_NAME = 'Rogue'
CLASS_PRIEST_NAME = 'Priest'
CLASS_DEATH_KNIGHT_NAME = 'Death Knight'
CLASS_SHAMAN_NAME = 'Shaman'
CLASS_MAGE_NAME = 'Mage'
CLASS_WARLOCK_NAME = 'Warlock'
CLASS_MONK_NAME = 'Monk'
CLASS_DRUID_NAME = 'Druid'
CLASS_DEMON_HUNTER_NAME = 'Demon Hunter'

# Class Colour Constants
CLASS_WARRIOR_COLOUR = 0xC79C6E
CLASS_PALADIN_COLOUR = 0xF58CBA
CLASS_HUNTER_COLOUR = 0xABD473
CLASS_ROGUE_COLOUR = 0xFFF569
CLASS_PRIEST_COLOUR = 0xFFFFFF
CLASS_DEATH_KNIGHT_COLOUR = 0xC41F3B
CLASS_SHAMAN_COLOUR = 0x0070DE
CLASS_MAGE_COLOUR = 0x69CCF0
CLASS_WARLOCK_COLOUR = 0x9482C9
CLASS_MONK_COLOUR = 0x00FF96
CLASS_DRUID_COLOUR = 0xFF7D0A
CLASS_DEMON_HUNTER_COLOUR = 0xA330C9
